<a href="https://colab.research.google.com/github/lochana454/DSC-assignment/blob/master/Numpy_Assignment_(4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])
a1
 
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2.0,3.4],[4,5,6.6]])
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.6]])

In [ ]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
a1=np.array([1,2,3])
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [ ]:
# Attributes of 2-dimensional array
a2=np.array([[1,2.0,3.4],[4,5,6.6]])
a2.shape,a2.ndim,a2.dtype,a2.size,type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [ ]:
# Create an array of shape (5, 5) with only ones
a=np.ones([5,5])
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Create an array of shape (3, 3, 5) with only zeros
a=np.zeros([3,3,5])
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
# Create a random array with numbers between 0 and 10 of size(7, 2)
import numpy as np
np.random.randint(10, size=(7, 2))

array([[6, 3],
       [7, 4],
       [6, 9],
       [2, 6],
       [7, 4],
       [3, 7],
       [7, 2]])

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
from numpy import random
X=random.rand(3,5)
X

array([[0.26579723, 0.11889876, 0.6742909 , 0.61982246, 0.80914206],
       [0.15073405, 0.73032986, 0.83644926, 0.80461747, 0.47694573],
       [0.4890068 , 0.77030263, 0.51249158, 0.17364561, 0.06533763]])

In [ ]:
# Create an array of normally distributed random numbers
np.random.randn(5, 3)

array([[-0.46947439,  0.54256004, -0.46341769],
       [-0.46572975,  0.24196227, -1.91328024],
       [-1.72491783, -0.56228753, -1.01283112],
       [ 0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 ]])

In [ ]:
# Set the random seed to 42
 
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(10, size=(4,6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [ ]:
# Copy the code from the cell above and run it again
np.random.seed(42)
a2=np.random.randint(10, size=(4,6))
a2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [ ]:
# Find the 0'th index of the latest array you created
a2[0,0]

6

In [ ]:
# Get the first 2 rows of latest array you created
a2[0:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
a2[:2,:2]

array([[6, 3],
       [2, 6]])

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
a1,a2=np.random.randint(10, size=(3,5)),np.ones( [3,5])

In [ ]:
# Add the two arrays together
a1+a2

array([[ 4.,  9.,  2., 10.,  9.],
       [10.,  5.,  2.,  4.,  7.],
       [ 8.,  3.,  1.,  4.,  2.]])

In [ ]:
# Create another array of ones of shape (5, 3)
b=np.ones([5,3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
a2+b

ValueError: ignored

In [ ]:
# Do the same operation you just did but this time with a transpose on one array
a2.T
c=a2.T+b
c

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
# Take the latest array to the power of 2 using the python way
c**2

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [ ]:
# Do the same thing with numpy way
np.square(c)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [ ]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
print("mean =",np.mean(c),"     ","min = ",np.min(c),"    ","max = ",np.max(c),"    ","standard deviation = ", np.sqrt(np.mean((c - np.mean(c)) ** 2 )),"     ","variance = ",np.mean((c - np.mean(c)) ** 2 ))

mean = 2.0       min =  2.0      max =  2.0      standard deviation =  0.0       variance =  0.0


In [ ]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
a =np.random.randint(10, size=(3,3))
z =np.random.randint(10, size=(3,2))
a , z

(array([[7, 3, 1],
        [5, 5, 9],
        [3, 5, 1]]), array([[9, 1],
        [9, 3],
        [7, 6]]))

In [ ]:
# Perform a dot product on the two newest arrays you created
np.dot(a,z)

array([[ 97,  22],
       [153,  74],
       [ 79,  24]])

In [ ]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
arr1 ,arr2=np.random.randint(10, size=(4,3)),np.random.randint(10, size=(4,3))

In [ ]:
# Perform a hadamard product on the two newest arrays you cr
np.multiply( arr1,arr2)

array([[32,  0,  4],
       [20, 72, 15],
       [ 8, 14,  0],
       [14,  2, 64]])

In [ ]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(arr1,arr2)

ValueError: ignored

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
np.dot(arr1,arr2.T)

array([[ 36,  42,  32,  72],
       [ 98, 107,  83,  68],
       [ 36,  54,  22,  64],
       [ 40,  64,  22,  80]])

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
A,B=np.random.randint(10, size=(3,4)),np.random.randint(10, size=(3,4))

In [ ]:
# Compare the two arrays with '>', '<=' and '==' 
print(A>B)
print(A<=B)
print(A==B)

[[ True  True  True False]
 [False  True  True False]
 [False  True False  True]]
[[False False False  True]
 [ True False False  True]
 [ True False  True False]]
[[False False False False]
 [ True False False False]
 [False False False False]]


In [ ]:
# Sort one of the arrays you just created in ascending order
np.sort(A)

array([[2, 5, 9, 9],
       [0, 1, 1, 9],
       [2, 6, 8, 9]])

In [ ]:
# Sort the indexes of one of the arrays you just created
np.argsort(B)

array([[1, 2, 3, 0],
       [2, 0, 1, 3],
       [1, 0, 3, 2]])

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
np.where(A == np.max(A))

(array([0, 0, 1, 2]), array([0, 1, 1, 1]))

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(A,axis=1)

array([0, 1, 1])

In [ ]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmax(A,axis=0)

array([0, 0, 2, 2])